### ISSUE TITLE
用您的代码在vs2019里打开，但是程序集里两个都是黄色感叹号

### ISSUE THREAD

**Issue by wtnu200** [axiu233/AxiuOpcua.ServerDemo#1]
DBInterfaceCommonLib，PECSDBInterface
是因为少了dll吗？哪里下载？
生成没有提示错误，运行起来后提示：Opc.Ua.ServiceResultException:“Error establishing a connection: BadNotConnected”

**Comment by axiu233** [comment]
不要管客户端代码,这只是个服务端示例.需要客户端的话可以去网上下载,一大堆
